//-----------------------------------------------------------
//-----------------------------------------------------------
//
//             System: IQFeed
//       Filename: SystemInfoSocket.java
//
//-----------------------------------------------------------
//
//            Proprietary Software Product
//
//           Data Transmission Network Inc.
//           9110 West Dodge Road Suite 200
//               Omaha, Nebraska  68114
//
//    Copyright (c) by Data Transmission Network 2008
//                 All Rights Reserved
//
//
//-----------------------------------------------------------
// Module Description: This file illustrates how to return various system calls 
//						that are needed by various processes within the API.
//         References: None
//           IDE: Netbeans 7.4
//             Author: Tim Walter
//        Modified By: 
//
//-----------------------------------------------------------
// Website for API information: http://www.iqfeed.net/dev/
//-----------------------------------------------------------
/******************************************************************************
 * DISCLAIMER:  These apps are designed with simplicity in mind and are not 
 * designed for copy and paste development.  You will need to consider 
 * performance enhancements based upon your own needs and implement your
 * solution accordingly. They are a guide to get people started, nothing more.
 ******************************************************************************/

import java.io.*;
import javax.swing.*;
import java.awt.event.*;

public class SystemInfoSocket extends javax.swing.JFrame implements ActionListener, WindowListener
{
    //Define variables for use throughout the code
    private int IQFEED_LOOKUP_PORT_DEFAULT = 9100;      //Defaults to 9100, adjustable in the registy.
	//IQFeed_Socket is defined in the common folder, effectively it is a socket with a buffered reader and writer added.
    IQFeed_Socket C_LookupIQFeed_Socket;
	/**
	 * Creates new form SystemInfoSocket
	 */
	public SystemInfoSocket()
	{
		super("System Info Socket");
		initComponents();
		C_LookupIQFeed_Socket = new IQFeed_Socket();

		//Attempt to connect our socket
		
		System.out.println("Connecting to Symbol Lookup port.");
			// requests a socket connection to localhost on port IQFEED_LOOKUP_PORT_DEFAULT, default = localhost and port 9100
		// Port 9100 is configurable in the registry.  See registry settings in the documentation.
		// If False is returned we are not able to connect display an error and exit. 
		if (!C_LookupIQFeed_Socket.ConnectSocket(IQFEED_LOOKUP_PORT_DEFAULT))
		{
			JOptionPane.showMessageDialog(null, "Did you forget to login first?\nTake a look at the LaunchingTheFeed example app.");
			System.exit(1);
		}

		System.out.println("Connected to Symbol Lookup port.");
		C_LookupIQFeed_Socket.CreateBuffers();

		//Initialize the protocol, this prepares us for commands to come and verifies that our socket is working as intended.
		try
		{
                        Java_Config config = new Java_Config();
			C_LookupIQFeed_Socket.brBufferedWriter.write(String.format("S,SET PROTOCOL,%s\r\n",config.most_recent_protocol));
			C_LookupIQFeed_Socket.brBufferedWriter.flush();
			System.out.println("Message Posted, Protocol set.");
		} catch (Exception eError)
		{
			updateCommandLabelError("Error writing to socket.\n%s", eError.toString());
		}

		Lookup_Listener thread = new Lookup_Listener();
		thread.start();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnGetTradeConditions = new javax.swing.JButton();
        lblDataSentToServer = new javax.swing.JLabel();
        btnGetSICCodeList = new javax.swing.JButton();
        btnGetNAICCodeList = new javax.swing.JButton();
        btnRequestListedMarkets = new javax.swing.JButton();
        btnRequestSecurityTypes = new javax.swing.JButton();
        btnGetMarketCenters = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDisplay = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGetTradeConditions.setText("Get Trade Conditions");
        btnGetTradeConditions.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGetTradeConditionsActionPerformed(evt);
            }
        });

        lblDataSentToServer.setText("Message Sent : ");

        btnGetSICCodeList.setText("Get SIC Code List");
        btnGetSICCodeList.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGetSICCodeListActionPerformed(evt);
            }
        });

        btnGetNAICCodeList.setText("Get NAICS Code List");
        btnGetNAICCodeList.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGetNAICCodeListActionPerformed(evt);
            }
        });

        btnRequestListedMarkets.setText("Request Listed Markets");
        btnRequestListedMarkets.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRequestListedMarketsActionPerformed(evt);
            }
        });

        btnRequestSecurityTypes.setText("Request Security Types");
        btnRequestSecurityTypes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRequestSecurityTypesActionPerformed(evt);
            }
        });

        btnGetMarketCenters.setText("Get Market Centers");
        btnGetMarketCenters.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGetMarketCentersActionPerformed(evt);
            }
        });

        txtDisplay.setColumns(20);
        txtDisplay.setRows(5);
        jScrollPane1.setViewportView(txtDisplay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDataSentToServer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGetSICCodeList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRequestListedMarkets, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnRequestSecurityTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGetNAICCodeList, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnGetTradeConditions, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(btnGetMarketCenters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRequestListedMarkets)
                    .addComponent(btnRequestSecurityTypes)
                    .addComponent(btnGetMarketCenters))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGetSICCodeList)
                    .addComponent(btnGetNAICCodeList)
                    .addComponent(btnGetTradeConditions))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDataSentToServer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	//-----------------------------------------------------------
	// void GetTradeConditionsActionPerformed(java.awt.event.ActionEvent evt)  
	/**
	 * @params Windows click event 
	 * Note: Send the "Get Trade Conditions" command.
	*/
	//-----------------------------------------------------------
    private void btnGetTradeConditionsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGetTradeConditionsActionPerformed
    {//GEN-HEADEREND:event_btnGetTradeConditionsActionPerformed
		//Message format: STC<CR><LF> 
		String sCommand = "STC\r\n";
		sendMessage(sCommand);
		//Clear txtDisplay and display aby messages
		txtDisplay.setText("");
		updateCommandLabelResult(sCommand);
    }//GEN-LAST:event_btnGetTradeConditionsActionPerformed
	//-----------------------------------------------------------
	// void GetSICCodeListActionPerformed(java.awt.event.ActionEvent evt)  
	/**
	 * @params Windows click event 
	 * Note: Send the "Get SIC Code Listing" command.
	*/
	//-----------------------------------------------------------
    private void btnGetSICCodeListActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGetSICCodeListActionPerformed
    {//GEN-HEADEREND:event_btnGetSICCodeListActionPerformed
		//Message format: SSC<CR><LF> 
		String sCommand = "SSC\r\n";
		sendMessage(sCommand);
		//Clear txtDisplay and display aby messages
		txtDisplay.setText("");
		updateCommandLabelResult(sCommand);
    }//GEN-LAST:event_btnGetSICCodeListActionPerformed
	//-----------------------------------------------------------
	// void GetNAICCodeListActionPerformed(java.awt.event.ActionEvent evt)  
	/**
	 * @params Windows click event 
	 * Note: Send the "Get NAIC Code" command.
	*/
	//-----------------------------------------------------------
    private void btnGetNAICCodeListActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGetNAICCodeListActionPerformed
    {//GEN-HEADEREND:event_btnGetNAICCodeListActionPerformed
		//Message format: SNC<CR><LF>  
		String sCommand = "SNC\r\n";
		sendMessage(sCommand);
		//Clear txtDisplay and display aby messages
		txtDisplay.setText("");
		updateCommandLabelResult(sCommand);
    }//GEN-LAST:event_btnGetNAICCodeListActionPerformed
	//-----------------------------------------------------------
	// void btnRequestListedMarketsActionPerformed(java.awt.event.ActionEvent evt)  
	/**
	 * @params Windows click event 
	 * Note: Send the "Request Listed Markets" command.
	*/
	//-----------------------------------------------------------
    private void btnRequestListedMarketsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRequestListedMarketsActionPerformed
    {//GEN-HEADEREND:event_btnRequestListedMarketsActionPerformed
		//Message format: SLM<CR><LF>  
		String sCommand = "SLM\r\n";
		sendMessage(sCommand);
		//Clear txtDisplay and display aby messages
		txtDisplay.setText("");
		updateCommandLabelResult(sCommand);
    }//GEN-LAST:event_btnRequestListedMarketsActionPerformed
	//-----------------------------------------------------------
	// void btnRequestSecurityTypesActionPerformed(java.awt.event.ActionEvent evt)  
	/**
	 * @params Windows click event 
	 * Note: Send the "Remove All Watches" command.
	*/
	//-----------------------------------------------------------
    private void btnRequestSecurityTypesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRequestSecurityTypesActionPerformed
    {//GEN-HEADEREND:event_btnRequestSecurityTypesActionPerformed
		//Message format: SST<CR><LF> 
		String sCommand = "SST\r\n";
		sendMessage(sCommand);
		//Clear txtDisplay and display aby messages
		txtDisplay.setText("");
		updateCommandLabelResult(sCommand);	
    }//GEN-LAST:event_btnRequestSecurityTypesActionPerformed
	//-----------------------------------------------------------
	// void btnGetMarketCentersActionPerformed(java.awt.event.ActionEvent evt)  
			/**
			 * Button click event to send the "Remove All Watches" command.
			 */
	//-----------------------------------------------------------
    private void btnGetMarketCentersActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGetMarketCentersActionPerformed
    {//GEN-HEADEREND:event_btnGetMarketCentersActionPerformed
		//Message format: SMC<CR><LF> 
		String sCommand = "SMC\r\n";
		sendMessage(sCommand);
		//Clear txtDisplay and display aby messages
		txtDisplay.setText("");
		updateCommandLabelResult(sCommand);	
    }//GEN-LAST:event_btnGetMarketCentersActionPerformed
	//-----------------------------------------------------------
	// void sendMessage(String sCommand) 

		/**
		 * Sends a command to the output stream for processing by the
 Lookup_Listener class\thread.
		 *
		 * @param sCommand, a String with a full message ready to be sent to the
		 * server including carriage return and line feed. Example: "S,UNWATCH
		 * ALL\r\n"
		 */
	//-----------------------------------------------------------     
	void sendMessage(String sCommand)
	{
		try
		{
			//Send the message and flush to be sure it is handled right away.
			C_LookupIQFeed_Socket.brBufferedWriter.write(sCommand);
			C_LookupIQFeed_Socket.brBufferedWriter.flush();
			//Label will show the actual string sent to the server.
			updateCommandLabelResult(sCommand);
		} catch (IOException eError)
		{
			updateCommandLabelError("Error:" + sCommand, eError.toString());
		}
	}
//-----------------------------------------------------------
//-----------------------------------------------------------
// void updateCommandLabelResult(String sCommand) 

	/**
	 * Displays a message to a user that identifies the full message being sent.
	 *
	 * @param sCommand, a String with a full message ready to be sent to the
	 * server including carriage return and line feed. Example: "S,UNWATCH
	 * ALL\r\n"
	 */
//-----------------------------------------------------------  
	void updateCommandLabelResult(String sCommand)
	{
		lblDataSentToServer.setText("Message Sent: " + sCommand);
	}
//-----------------------------------------------------------
// void updateCommandLabelError(String sCommand, String sError) 

	/**
	 * Displays a message to a user that identifies the error that may have
	 * occured.
	 *
	 * @param sCommand, a String with a full message ready to be sent to the
	 * server including carriage return and line feed. Example: "S,UNWATCH
	 * ALL\r\n"
	 * @param sError, a String passed from the exception object.
	 */
//-----------------------------------------------------------   
	void updateCommandLabelError(String sCommand, String sError)
    {
        String sErrorMessage = String.format("%s \n Error Message: %s",sCommand, sError);
        lblDataSentToServer.setText(sErrorMessage); 
    }    
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try
		{
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(SystemInfoSocket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(SystemInfoSocket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(SystemInfoSocket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(SystemInfoSocket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>
		
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new SystemInfoSocket().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetMarketCenters;
    private javax.swing.JButton btnGetNAICCodeList;
    private javax.swing.JButton btnGetSICCodeList;
    private javax.swing.JButton btnGetTradeConditions;
    private javax.swing.JButton btnRequestListedMarkets;
    private javax.swing.JButton btnRequestSecurityTypes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDataSentToServer;
    private javax.swing.JTextArea txtDisplay;
    // End of variables declaration//GEN-END:variables
 /******************************************************************
 ******************************************************************
 ******************************************************************/
//-----------------------------------------------------------
// void actionPerformed(ActionEvent e)
// void windowOpened(WindowEvent e)
// void windowClosing(WindowEvent e)
// void windowIconified(WindowEvent e)
// void windowDeiconified(WindowEvent e)
// void windowClosed(WindowEvent e)
// void windowActivated(WindowEvent e)
// void windowActivated(WindowEvent e)        
/**
 * These 8 Window's event functions are left effectively blank due to simplicity, but are required for compilation.
*/
//-----------------------------------------------------------
// Start of Window's events.
    @Override
    public void actionPerformed(ActionEvent e)
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowOpened(WindowEvent e)
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowClosing(WindowEvent e)
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowClosed(WindowEvent e)
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowIconified(WindowEvent e)
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeiconified(WindowEvent e)
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    @Override
    public void windowActivated(WindowEvent e)
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    @Override
    public void windowDeactivated(WindowEvent e)
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    //End of window's events
    /******************************************************************
    ******************************************************************
    ******************************************************************/
	
	    
    
    //Class to execute and listen to replies from the server.
    //I am displaying the data returned in this function for simplicity to the text Window.
    //Considerations for performance will be needed as this will not work for most normal usage.
    class Lookup_Listener extends Thread
    {
    //-----------------------------------------------------------
    // void run()
    /**
    */
    //  Notes:  Check for data on the socket, process it if it exists by displaying
    //          to the text window.
    //
    //-----------------------------------------------------------
            public void run()
            {
                    String line;
                    try
                    {
                            while ((line = C_LookupIQFeed_Socket.brBufferedReader.readLine()) != null)
                            {
                                    System.out.println(line);
                                    txtDisplay.append(line + "\n");
                            }
                    }
                    catch (Exception eError) 
                    { 
                        updateCommandLabelError("Unable to read from socket.\n" , eError.toString());
                    }
            }
    }
}
